"use strict";
const $=id=>document.getElementById(id);let token='',fields=[],review=null,busy=false;
const node=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!r.ok)throw Error('Request was rejected or failed. Refresh saved status before taking another action.');return r.json();}
async function action(work){if(busy)return;busy=true;$('message').textContent='';try{await work();}catch(e){$('message').textContent=e.message;}finally{busy=false;}}
function display(r){review=r;location.hash=r.id;$('review').hidden=false;$('status').textContent=r.status.replaceAll('_',' ');$('scope').replaceChildren();for(const f of fields){const s=r.selections[f.id];$('scope').append(node('dt',f.label),node('dd',s.mode==='all'?'All values':s.values.join(', ')));}$('confirm').checked=false;$('approve').hidden=r.status!=='DRAFT_REQUIRES_REVIEW';$('confirmation').hidden=$('approve').hidden;$('run').hidden=r.status!=='APPROVED';$('result').replaceChildren();if(r.result){$('result').append(node('h3','Saved comparison'),node('p',r.result.comparison_status+' - '+r.result.selected_records+' selected records'));for(const [currency,impact] of Object.entries(r.result.impact_by_currency))$('result').append(node('p',currency+': Silver '+impact.silver_total+'; Gold '+impact.gold_total+'; difference '+impact.downstream_minus_upstream));$('result').append(node('p',r.result.limitation));}}
$('connect').onsubmit=e=>{e.preventDefault();action(async()=>{token=$('token').value;$('token').value='';const c=await api('/api/context');fields=c.fields;$('report').textContent=c.report;$('fields').replaceChildren();fields.forEach((f,i)=>{const label=node('label',f.label);label.htmlFor='mode'+i;const select=document.createElement('select');select.id='mode'+i;select.required=true;select.append(new Option('Choose selection',''),new Option('All values','all'),new Option('Specific values','values'));const valueLabel=node('label','Values (one per line)');valueLabel.htmlFor='values'+i;const values=document.createElement('textarea');values.id='values'+i;values.rows=3;values.hidden=valueLabel.hidden=true;select.onchange=()=>{values.hidden=valueLabel.hidden=select.value!=='values';values.required=select.value==='values';};$('fields').append(label,select,valueLabel,values);});$('login').hidden=true;$('choices').hidden=false;if(location.hash)display(await api('/api/reviews/'+location.hash.slice(1)));});};
$('prepare').onsubmit=e=>{e.preventDefault();action(async()=>{const selections={};fields.forEach((f,i)=>{const mode=$('mode'+i).value;selections[f.id]=mode==='all'?{mode}:{mode,values:$('values'+i).value.split('\n').map(s=>s.trim()).filter(Boolean)};});display(await api('/api/reviews',{selections}));});};
$('approve').onclick=()=>action(async()=>{if(!$('confirm').checked)throw Error('Review the selections and check the confirmation box.');display(await api('/api/reviews/'+review.id+'/approve',{confirm:true,scope_hash:review.scope_hash}));});
$('run').onclick=()=>action(async()=>display(await api('/api/reviews/'+review.id+'/run',{confirm:true,scope_hash:review.scope_hash})));
$('refresh').onclick=()=>action(async()=>display(await api('/api/reviews/'+review.id)));
