'use strict';
const $=id=>document.getElementById(id);
let token='',snapshot=null,caseId=null,poll=null,requestKey=crypto.randomUUID();
const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value));
function view(name){for(const section of document.querySelectorAll('.view'))section.hidden=section.id!==name;for(const button of document.querySelectorAll('nav button'))button.setAttribute('aria-current',String(button.dataset.view===name));window.scrollTo(0,0);}
for(const button of document.querySelectorAll('nav button'))button.onclick=()=>view(button.dataset.view);
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw Error(data.error||'Unable to complete this request');return data;}
function message(error){$('message').textContent=error.message;}
$('login-form').onsubmit=async event=>{event.preventDefault();try{token=$('token').value;$('token').value='';snapshot=await api('/api/report');$('login').hidden=true;$('workspace').hidden=false;renderSnapshot();view('orders');if(location.hash){caseId=location.hash.slice(1);view('investigator');await refresh();}}catch(error){message(error);}};
function renderSnapshot(){ $('payments').textContent=money(snapshot.payments);$('refunds').textContent=money(snapshot.refunds);$('balance').textContent=money(Number(snapshot.payments)-Number(snapshot.refunds));$('reported').textContent=money(snapshot.reported);$('selected-amount').textContent=money(snapshot.reported);$('report-ref').textContent=snapshot.id.slice(0,8);$('report-time').textContent='Captured '+new Date(snapshot.captured_at).toLocaleTimeString();$('order-rows').replaceChildren();for(const order of snapshot.orders){const tr=document.createElement('tr');for(const text of [order.order_id,money(order.captured_amount),money(order.refunded_amount),money(Number(order.captured_amount)-Number(order.refunded_amount))]){const td=document.createElement('td');td.textContent=text;tr.append(td);}$('order-rows').append(tr);}}
$('open-report').onclick=()=>view('report');$('ask-report').onclick=()=>view('investigator');
for(const [input,preview] of [['report-shot','report-preview'],['app-shot','app-preview']]){$(input).onchange=()=>{const file=$(input).files[0];if($(preview).src)URL.revokeObjectURL($(preview).src);$(preview).hidden=!file;if(file)$(preview).src=URL.createObjectURL(file);requestKey=crypto.randomUUID();};}
$('question').oninput=()=>{requestKey=crypto.randomUUID();};
async function file64(id){const file=$(id).files[0];if(!file)return null;if(file.size>3000000||file.type!=='image/png')throw Error('Please attach a PNG smaller than 3 MB.');return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(Error('Could not read screenshot'));reader.readAsDataURL(file);});}
$('case-form').onsubmit=async event=>{event.preventDefault();$('submit').disabled=true;$('message').textContent='';try{const body={snapshot_id:snapshot.id,question:$('question').value,screenshot:await file64('report-shot'),app_screenshot:await file64('app-shot'),request_key:requestKey};const data=await api('/api/cases',body);caseId=data.id;location.hash=caseId;$('intake').hidden=true;$('progress').hidden=false;$('progress-title').textContent='Checking your report';$('case-status').textContent='In progress';await refresh();}catch(error){message(error);$('submit').disabled=false;}};
async function refresh(){clearTimeout(poll);try{const item=await api('/api/cases/'+caseId);$('intake').hidden=true;$('progress').hidden=false;$('case-question').textContent=item.question;$('case-status').textContent=item.status==='RUNNING'?'In progress':item.status==='COMPLETED'?'Complete':'Needs review';$('steps').replaceChildren();for(const step of item.steps){const li=document.createElement('li');li.textContent=step.text+' · '+new Date(step.at).toLocaleTimeString();$('steps').append(li);}if(item.status==='RUNNING'){poll=setTimeout(refresh,400);return;}$('progress-title').textContent=item.status==='COMPLETED'?'Investigation complete':'A reviewer is needed';if(item.status!=='COMPLETED'){$('message').textContent=item.result?.message||'This investigation was interrupted. Please start a fresh report check.';return;}const result=item.result;$('result').hidden=false;$('headline').textContent=result.headline;$('explanation').textContent=result.explanation;$('result-reported').textContent=money(result.reported);$('result-expected').textContent=money(result.expected);$('result-difference').textContent=money(result.difference);$('affected').replaceChildren();for(const order of result.affected_orders){const p=document.createElement('p');p.textContent=order.order_id+' · Report difference '+money(order.downstream_minus_upstream);$('affected').append(p);}if(!result.affected_orders.length)$('affected').textContent='No differing orders found.';$('next-action').textContent=result.next_action;$('technical').textContent=JSON.stringify(result.technical,null,2);$('limitation').textContent=result.limitation;$('attachment-proof').textContent='Report screenshot retained. Reference: '+item.screenshot_sha256.slice(0,16)+(item.application_screenshot_attached?' · Order screenshot also retained.':'');}catch(error){message(error);}}
